#server:
#  port: 8081
#spring:
#  zipkin:
#    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
#    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
#  sleuth:
#    sampler:
#      probability: 1.0 #采样的百分比
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: service-product
#  profiles:
#    active: db
##mybatis 配置自动建表，系统会自动判断哪些表是新建的，哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据。
#mybatis:
#  table:
#    auto: update
#  model:
#    pack: cn.edu.neusoft.model
#  database: mysql
#  mybatis-plus:
#    mapper-locations: classpath:/mapper/*mapper.xml
#
#
#
